### ISSUE TITLE
Lapse count of cards

### ISSUE THREAD

**Issue by l3kn** [open-spaced-repetition/py-fsrs#17]
In the `update_state` function at https://github.com/open-spaced-repetition/py-fsrs/blob/main/src/fsrs/models.py#L87
the lapse count of a card is only incremented for cards in the `new` and `review` state.

Is this a bug or the intended behavior? Anki seems to increment the lapse count only for `review` card.

While this is not relevant for the core logic of the algorithm, I'm trying to reimplement FSRS in EmacsLisp
and I'd like to understand the motivation behind this behavior.

**Comment by L-M-Sherlock** [comment]
It is a bug. I will fix it soon.
