### ISSUE TITLE
f.p.w 默认参数会不会在用户复习数千次后变化？

### ISSUE THREAD

**Issue by zxl777** [open-spaced-repetition/py-fsrs#26]
如果 f.p.w 会变好，在什么时机保存为好？ 或者f.p.w在哪个时候会变化？

**Comment by L-M-Sherlock** [comment]
不会变化，因为 py-fsrs 不包含优化器。

**Comment by zxl777** [comment]
那么如果我想优化这个参数，是等py-fsrs升级？

还是 用这个 [fsrs4anki_optimizer.ipynb](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb)

**Comment by L-M-Sherlock** [comment]
这个依赖 PyTorch 深度学习库，算力要求很高。另外需要你记录用户的复习日志。

**Comment by zxl777** [comment]
我有GPU服务器在运行，
我按Anki的数据库格式来记录用户的复习日志，这样应该就可以用[fsrs4anki_optimizer.ipynb](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb) 了吧？

**Comment by zxl777** [comment]
用优化器，能带来多少好处呢？

**Comment by L-M-Sherlock** [comment]
支持fsrs- optimizer那个仓库约定的数据格式即可。预测误差可以降低20%
