### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by oschlueter** [open-spaced-repetition/py-fsrs#27]
Hey!

Thank you for providing the means to build spaced repetition applications! I'd like to build a simple web app to repeat chess exercises and want to use your library for this purpose. Unfortunately, I have no idea how I would include it. 

How can I create `Card` objects with my custom data?

Also, how do I store the result of a repetition set and load it again when I go for the next repetition?

I'd love to contribute a PR for a README and help others understand this quickly as well. Unfortunately, right now I don't understand it myself. Looking forward to your support!

**Comment by L-M-Sherlock** [comment]
> How can I create `Card` objects with my custom data?

What's. your custom data? I recommend using `Card` only for scheduling and storing contents and other data in other table/object.

**Comment by oschlueter** [comment]
My custom data is a dictionary of strings, e.g. a chess position in FEN notation.

After practicing my chess, I could store the `Card` objects to disk but when I go again, the `__init__` would set all member variables to 0. I suppose I would need to change the constructor of `Card` to load the data from the previous practice. What do you think?

**Comment by L-M-Sherlock** [comment]
You need to implement your own constructor, which is based on the database or ORM that you plan to use.

**Comment by oschlueter** [comment]
Thank you for the advice! I finished my implementation. In case anyone else wants to take a look, you can find it [here](https://github.com/oschlueter/chess-tactics-cards).

And thanks again for this wonderful library!
