### ISSUE TITLE
[Feature request]: Make Card objects JSON serializable

### ISSUE THREAD

**Issue by joshdavham** [open-spaced-repetition/py-fsrs#32]
Up till now, I've been using python's pickle module to save my Card objects as files in a blob storage, but I'd like to move them into a no-sql database instead.

The problem however, is that there's currently no good way to serialize Card objects to be stored in (and then later reconstructed from) a database. I originally looked into just storing my Card objects as byte strings with `pickle.dumps(card_object)`, but this is apparently bad practice as one's application can be harder to debug and the pickled object can now only be reconstructed in python and not in other languages.

I implemented a feature today in my fork of py-fsrs that can make Card objects JSON serializable in a backwards-compatible way (no breaking changes this time!). Am I good to open a PR for this?

**Comment by L-M-Sherlock** [comment]
PR is welcome!

**Comment by joshdavham** [comment]
PR #33
