### ISSUE TITLE
[question] 对init_stability方法的疑问

### ISSUE THREAD

**Issue by doveeeee** [open-spaced-repetition/py-fsrs#35]
[这段代码](https://github.com/open-spaced-repetition/py-fsrs/blame/main/src/fsrs/fsrs.py#L90)在点击again时会取到`self.p.w[0 - 1]`，也就是`self.p.w[-1]`，最终的值为`2.61`，请问这是符合预期的吗？
以下是源代码片段：
```python
    def init_stability(self, r: int) -> float:
        return max(self.p.w[r - 1], 0.1)
```

望解答，十分感谢！

**Comment by ishiko732** [comment]
你好，点击again的时候，`Rating.Again=1`。如果是默认参数的话应该是`0.4` ：

https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/models.py#L14-L18

https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/models.py#L252-L269

**Comment by doveeeee** [comment]
> 你好，点击again的时候，`Rating.Again = 1`。如果是默认参数的话应该是`0.4` ：
> 
> https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/models.py#L14-L18
> 
> https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/models.py#L252-L269

明白了！ 是我的疏忽，十分抱歉！ 很久以前引用过这段代码的旧版本，但在更新V4后他从`0、1、2、3`变成了`1、2、3、4`

我在更新这段代码时疏忽了此处的改动导致了这个问题，再次表示歉意，浪费了您的宝贵时间，同时也感谢您的解答~
