### ISSUE TITLE
fsrs.repeat会导致输入的card信息被修改

### ISSUE THREAD

**Issue by ishiko732** [open-spaced-repetition/py-fsrs#4]
在`test.py`中:
https://github.com/open-spaced-repetition/py-fsrs/blob/464543779f7e8ebaca18697cdf84fe8cd0dc766d/tests/test_fsrs.py#L26-L31

在29行开始做修改:
```python
    card = scheduling_cards[Rating.Good].card
    good_card = card
    print(good_card.__dict__)
    now = card.due
    scheduling_cards = f.repeat(card, now)
    print(good_card.__dict__)
``` 
打印的结果发生改变:
![image](https://user-images.githubusercontent.com/62931549/222968820-3556754d-1cdb-4318-b2d7-b067f13ddc42.png)

应当在`fsrs.py`的`repeat`添加`card = copy.deepcopy(card)`:
```python
    def repeat(self, card: Card, now: datetime) -> dict[int, SchedulingInfo]:
        card = copy.deepcopy(card)
        if card.state == State.New:
```

**Comment by L-M-Sherlock** [comment]
OK 明天修一下
