### ISSUE TITLE
[TODO] switch of enable/disable short-term schedule

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/py-fsrs#56]
The implementation of ts-fsrs:
- https://github.com/open-spaced-repetition/ts-fsrs/pull/100

**Comment by joshdavham** [comment]
Can I get some more context on this? I have a lot of trouble reading typescript.

**Comment by L-M-Sherlock** [comment]
I also implemented the Golang version: 

- https://github.com/open-spaced-repetition/go-fsrs/pull/20

**Comment by joshdavham** [comment]
Code aside, at a high level, what is this new long / short term scheduler thing? Is it described anywhere else other than in source code?

**Comment by L-M-Sherlock** [comment]
@ishiko732 , do we have the diagram?

**Comment by ishiko732** [comment]
> do we have the diagram?

Currently, there isn’t one available; it might take some time to create a diagram.

**Comment by ishiko732** [comment]
I have updated the diagram, and you can download the original file from the following link: https://drive.google.com/file/d/1oigP0bheX9cXOO9baqwDTzAZ9IWvpCio/view?usp=sharing

**Comment by ishiko732** [comment]
Long-term Scheduler WorkFlow:
![ts-fsrs-workflow-Long-term Scheduler WorkFlow drawio](https://github.com/user-attachments/assets/a7c89b9e-2d88-45a0-8721-45ba825962b3)

Enable_short_term:
![ts-fsrs-workflow-enable_short_term drawio](https://github.com/user-attachments/assets/96b16fb1-559f-4122-95c3-28130be8c44a)

**Comment by ishiko732** [comment]
Short-term Scheduler:
![ts-fsrs-workflow-Short-term Scheduler Sequence  drawio](https://github.com/user-attachments/assets/bf27bb36-0342-4e14-9175-8f98569c1572)

Long-term Scheduler:
![ts-fsrs-workflow-Long-term Scheduler Sequence drawio](https://github.com/user-attachments/assets/4c0c0c21-6b0b-4e68-bd45-e8951148d476)

**Comment by domino14** [comment]
And what does it mean? I thought the interval times were inherent to the algorithm. Do the different schedulers have different constants?

**Comment by joshdavham** [comment]
@domino14 py-fsrs currently only has one scheduler. You can take a look at [ALGORITHM.md](https://github.com/open-spaced-repetition/py-fsrs/blob/main/ALGORITHM.md) for details.

As for the new long term scheduler option, which isn't implemented yet, there will be no learning/relearning state for the cards and furthermore, rating a card again, may not necessarily cause it to be due again in the same day, as the interval may be longer (e.g., 2 days, 6 days). The long term scheduler will be sorta be a more 'natural' version of fsrs with less rules.

**Comment by domino14** [comment]
Thanks for the response; I’m actually using the Go version but liked
looking at this code since it is better documented. The long term scheduler
for the Go version has no learning / relearning states?

**Comment by joshdavham** [comment]
@domino14 It'd be best to ask that question in the Go repo.

**Comment by joshdavham** [comment]
#64 V4 of Py-FSRS now uses learning and relearning steps. If you'd like to enable something like the 'long-term scheduler', you can disable the re/learning steps by leaving them blank.

```python
scheduler = Scheduler(learning_steps=(), relearning_steps=()
```
