### ISSUE TITLE
[TODO] Fuzz

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/py-fsrs#60]
Related code in ts-fsrs

https://github.com/open-spaced-repetition/ts-fsrs/blob/c0e4d68681024666dad3f8cdbd3a6a9fca73e5bf/src/fsrs/algorithm.ts#L130-L147

**Comment by Brentably** [comment]
What's the latest on this?

**Comment by joshdavham** [comment]
@Brentably I’m currently working on a refactoring of this repo and fuzz will be part of the refactor. I’m hoping to have PR open sometime tomorrow.

**Comment by Brentably** [comment]
Awesome! Thanks so much!
ᐧ

**Comment by joshdavham** [comment]
#64 Interval fuzzing is now enabled by default in v4.
