### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by williamjr** [open-spaced-repetition/py-fsrs#70]
Hello, thanks for your work on this awesome project!

As a newcomer, one thing I've been scratching my head about a bit is how this package should best be integrated into an application. In particular, a RESTful backend service, eg FastAPI or Flask, which uses an open source RDBMS, eg Postgres, via an ORM layer like SQLModel or SQLAlchemy.

I doubt I'm the only one with these questions. I wonder if it would be worth adding or pointing to example apps that use the project?

**Comment by joshdavham** [comment]
@williamjr Hey man long time no see!

> [...] FastAPI or Flask, which uses an open source RDBMS, eg Postgres, via an ORM layer like SQLModel or SQLAlchemy.

There's a [section](https://github.com/open-spaced-repetition/py-fsrs?tab=readme-ov-file#serialization) in the README that mentions that `Card` objects, etc are json-serializable and thus should be able to be stored in most databases. 

Regarding, providing guidance on integrating py-fsrs into a backend, I guess if someone builds an app with minimal boilerplate and open sources it, we could provide a link to it. We do have an [awesome-fsrs](https://github.com/open-spaced-repetition/awesome-fsrs) repo where we provides links like this. Maybe it could go there.

**Comment by williamjr** [comment]
Hello @joshdavham fancy seeing you here, and thanks for the reply.

I took a spin through [awesome-fsrs](https://github.com/open-spaced-repetition/awesome-fsrs). I wouldn't personally view any of those apps as particularly easy to follow examples... would you?

**Comment by joshdavham** [comment]
> I wouldn't personally view any of those apps as particularly easy to follow examples... would you?

Nope, me neither.

But to get to the root of your issue, you're basically looking for something like a guide on how to build a full stack web app using py-fsrs, or at least, an example of one that already exists?

**Comment by williamjr** [comment]
I would propose that py-fsrs would do well to show usage examples in a real-world context. Maintainers might decide this is out of scope, which would be fine! But that might limit adoption and accessibility of the project.

In terms of how much of the stack to show, I'm not sure whether a UI is essential. But a database layer, and a RESTful API seem like table stakes.

**Comment by joshdavham** [comment]
You make some good points. It definitely would be helpful for backend web devs to have some examples to go off.

With that being said, I personally think this is a bit out of scope for the project (at least right now). I'd ideally like to keep py-fsrs mostly agnostic as to what developers will be using it for - whether that's web apps, desktop apps, experimentation/research, etc.

If it's maybe the high-level flow of how to build with py-fsrs that you're wondering about, the basic flow is
1. Create a card
2. Review that card
3. Save that card
4. Review that card again when it's due
5. Then repeat steps 3-4

Now how this is implemented is ultimately left to the dev.
