### ISSUE TITLE
[TODO] clip post-lapse stability

### ISSUE THREAD

**Issue by ishiko732** [open-spaced-repetition/py-fsrs#71]
- https://github.com/open-spaced-repetition/fsrs-rs/pull/257
- https://github.com/open-spaced-repetition/go-fsrs/pull/30
- https://github.com/open-spaced-repetition/ts-fsrs/pull/142

**Comment by joshdavham** [comment]
Thanks for letting me know! I can take a look at this tmo and I'll let you know if I have any questions.
